#!/usr/bin/env bash
# Pulls the APP Postgres credentials for blablarags-prod-postgres (RDS) from
# AWS Secrets Manager and writes them to .env.aws.rds in the exact var names
# server/src/config.ts requires (DB_HOST, DB_PORT, POSTGRES_USER,
# POSTGRES_PASSWORD, POSTGRES_DB, DB_SSL). Deliberately fetches the APP
# secret, not the admin one — this file is meant to point the running
# server at RDS, and the server must never hold the RDS master credential.
#
# .env.aws.rds is gitignored and disposable — delete it anytime, rerun this
# script to regenerate. Usage:
#   scripts/aws-fetch-db-secret.sh
#   npm run dev:executemigration --prefix server -- --env-file=../.env.aws.rds --backup
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AWS_PROFILE="terraform-deploy"
AWS_REGION="eu-central-1"
SECRET_ID="blablarags-prod-postgres-app-credentials"
OUT_FILE="$ROOT_DIR/.env.aws.rds"

command -v aws >/dev/null 2>&1 || { echo "aws CLI not found." >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "python3 not found (needed to parse the secret JSON)." >&2; exit 1; }

SECRET_JSON="$(aws secretsmanager get-secret-value \
  --secret-id "$SECRET_ID" \
  --profile "$AWS_PROFILE" --region "$AWS_REGION" \
  --query SecretString --output text)"

DB_HOST="$(echo "$SECRET_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["host"])')"
DB_PORT="$(echo "$SECRET_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["port"])')"
DB_USER="$(echo "$SECRET_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["username"])')"
DB_PASSWORD="$(echo "$SECRET_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["password"])')"
DB_NAME="$(echo "$SECRET_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["dbname"])')"

cat > "$OUT_FILE" <<EOF
# Generated by scripts/aws-fetch-db-secret.sh on $(date -Iseconds 2>/dev/null || date)
# Points server/src/config.ts at the real AWS RDS instance instead of the
# local Docker Postgres container. Gitignored, disposable — regenerate by
# rerunning that script.
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=${DB_NAME}
DB_SSL=true
EOF

chmod 600 "$OUT_FILE"
echo "Wrote ${OUT_FILE} (host=${DB_HOST}, db=${DB_NAME}, user=${DB_USER})"
