#!/usr/bin/env bash
# Runs ON the EC2 instance (via `aws ssm send-command`, never over SSH — see
# infra/terraform/environments/prod/ec2.tf). Assembles /opt/blablarags/.env
# from Secrets Manager (using the instance's own IAM role, no credentials
# passed in), logs into GHCR, and brings up docker-compose.prod.yml.
#
# Idempotent — safe to re-run on every deploy. Installs `aws` CLI on first
# run if missing (not baked into the original user_data).
set -euo pipefail

AWS_REGION="eu-central-1"
APP_DIR="/opt/blablarags"
ENV_FILE="${APP_DIR}/.env"

if ! command -v aws >/dev/null 2>&1; then
  echo "Installing AWS CLI v2 (not in apt's default repos on this AMI)..."
  apt-get update -y
  apt-get install -y unzip curl
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o /tmp/awscliv2.zip
  unzip -q -o /tmp/awscliv2.zip -d /tmp
  /tmp/aws/install
  rm -rf /tmp/awscliv2.zip /tmp/aws
fi

mkdir -p "$APP_DIR"
cd "$APP_DIR"

echo "Fetching secrets from Secrets Manager..."
DB_JSON="$(aws secretsmanager get-secret-value --secret-id blablarags-prod-postgres-app-credentials --region "$AWS_REGION" --query SecretString --output text)"
RUNTIME_JSON="$(aws secretsmanager get-secret-value --secret-id blablarags-prod-app-runtime --region "$AWS_REGION" --query SecretString --output text)"
GHCR_TOKEN="$(aws secretsmanager get-secret-value --secret-id blablarags-prod-ghcr-pull-token --region "$AWS_REGION" --query SecretString --output text)"

# Plain text (not JSON) — an APR1-MD5 htpasswd file, one user:hash per
# line. Gates web.blablarags.com/admin.blablarags.com during pre-launch.
mkdir -p "${APP_DIR}/nginx/secrets"
aws secretsmanager get-secret-value --secret-id blablarags-prod-nginx-basic-auth --region "$AWS_REGION" --query SecretString --output text > "${APP_DIR}/nginx/secrets/.htpasswd"
# 644, not 600: nginx's worker processes run as an unprivileged user
# (dropped from root), so 600 (owner/root-only) makes this unreadable to
# them — only the .env file (plaintext secrets) needs to stay
# root-only; this file holds APR1-MD5 hashes, not plaintext.
chmod 644 "${APP_DIR}/nginx/secrets/.htpasswd"

DB_HOST="$(echo "$DB_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["host"])')"
DB_PORT="$(echo "$DB_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["port"])')"
DB_USER="$(echo "$DB_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["username"])')"
DB_PASSWORD="$(echo "$DB_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["password"])')"
DB_NAME="$(echo "$DB_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["dbname"])')"

COOKIE_SECRET="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["cookie_secret"])')"
JWT_ACCESS_SECRET="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["jwt_access_secret"])')"
JWT_REFRESH_SECRET="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["jwt_refresh_secret"])')"
PAYMENT_ENCRYPTION_KEY="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["payment_encryption_key"])')"
R2_ENDPOINT="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["r2_endpoint"])')"
R2_ACCESS_KEY="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["r2_access_key"])')"
R2_SECRET_KEY="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["r2_secret_key"])')"
R2_BUCKET="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["r2_bucket"])')"
CDN_BASE_URL="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["cdn_base_url"])')"
GRAFANA_ADMIN_PASSWORD="$(echo "$RUNTIME_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["grafana_admin_password"])')"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy-to-ec2.sh — do not edit by hand, regenerate by
# rerunning a deploy.
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=${DB_NAME}
COOKIE_SECRET=${COOKIE_SECRET}
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
PAYMENT_ENCRYPTION_KEY=${PAYMENT_ENCRYPTION_KEY}
R2_ENDPOINT=${R2_ENDPOINT}
R2_ACCESS_KEY=${R2_ACCESS_KEY}
R2_SECRET_KEY=${R2_SECRET_KEY}
R2_BUCKET=${R2_BUCKET}
MINIO_PUBLIC_URL_BASE=${CDN_BASE_URL}
CDN_BASE_URL=${CDN_BASE_URL}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
EOF
chmod 600 "$ENV_FILE"

echo "Logging into ghcr.io..."
echo "$GHCR_TOKEN" | docker login ghcr.io -u leonmex --password-stdin

echo "Pulling and starting the stack..."
docker compose -f "${APP_DIR}/docker-compose.prod.yml" pull
docker compose -f "${APP_DIR}/docker-compose.prod.yml" up -d

echo "Deploy complete."
docker compose -f "${APP_DIR}/docker-compose.prod.yml" ps
