#!/usr/bin/env bash
# One-shot bootstrap for the DEVELOPMENT stack (docker-compose.yml).
#
# Generates whatever is missing to go from a bare checkout to a running,
# LAN-reachable stack: a `.env` with working defaults (dbPostgres/minio
# refuse to boot without one — see server/src/config.ts's `required()`
# calls), the self-signed TLS cert nginx/default.conf's :443 server
# expects, and a preflight check that reroutes any host port already held
# by some OTHER process/project (docker-compose.yml's ports are all
# `${HOST_..._PORT:-default}`, so this only ever touches .env, never the
# compose file). Without that check, `docker compose up` fails partway
# through with a bare "port is already allocated" and leaves a half
# -started stack behind.
#
# The proxy service publishes its ports without a host-IP prefix, which
# Docker binds to 0.0.0.0 — reachable from any device on the LAN as soon as
# the host firewall allows it. This script does not touch the firewall; it
# only reports the URLs and reminds you to open the ports if another
# device can't reach them.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

DETACH=1
for arg in "$@"; do
  case "$arg" in
    --foreground|-f) DETACH=0 ;;
    *)
      echo "Usage: $0 [--foreground]" >&2
      exit 1
      ;;
  esac
done

command -v docker >/dev/null 2>&1 || { echo "Docker is not installed or not on PATH." >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "The 'docker compose' plugin (v2) is required." >&2; exit 1; }

# ---------------------------------------------------------------------------
# .env — required before anything can boot (server/src/config.ts hard-fails
# without POSTGRES_*; dbPostgres/minio have no built-in defaults either).
# ---------------------------------------------------------------------------
if [ ! -f .env ]; then
  echo "No .env found — generating one with fresh random credentials..."
  POSTGRES_PASSWORD="$(openssl rand -hex 16)"
  MINIO_ROOT_PASSWORD="$(openssl rand -hex 16)"
  cat > .env <<EOF
# Auto-generated by scripts/star-from-cero.sh on $(date -Iseconds 2>/dev/null || date)
# Safe to edit — docker compose reads this on every 'up'.

# Dashboard source mounted into the webapp container (see root CLAUDE.md).
APP_ROUTE=./dashboard

# PostgreSQL (dbPostgres service + server/src/config.ts).
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=test

# MinIO object storage (server uploads).
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_BUCKET=blablarags-apparel

# Host ports — scripts/star-from-cero.sh rewrites these below if something
# else on this machine already holds one of them.
HOST_HTTP_PORT=80
HOST_HTTPS_PORT=443
HOST_PROXY_PORT_4321=4321
HOST_PROXY_PORT_3000=3000
HOST_MAILHOG_PORT=8025
HOST_DEBUG_PORT=9229
HOST_POSTGRES_PORT=5432
HOST_REDIS_PORT=6379
HOST_MINIO_CONSOLE_PORT=9001
HOST_WEBSITE_PORT=4322
EOF
  echo "  -> .env created."
else
  echo ".env already exists — leaving your values untouched."
fi

# ---------------------------------------------------------------------------
# TLS certificate — nginx/default.conf's :443/:4321/:3000 server blocks fail
# to start without it.
# ---------------------------------------------------------------------------
if [ ! -f nginx/certs/server.crt ] || [ ! -f nginx/certs/server.key ]; then
  echo "No TLS certificate found — generating a self-signed one..."
  "$ROOT_DIR/scripts/generate-certs.sh"
else
  echo "TLS certificate already present — leaving it untouched."
fi

# ---------------------------------------------------------------------------
# Port preflight — detect conflicts with anything NOT part of this project
# and reroute them in .env before `docker compose up` ever runs.
# ---------------------------------------------------------------------------
get_env_var() {
  local key="$1" default="$2" val
  val="$(grep -E "^${key}=" .env 2>/dev/null | tail -1 | cut -d'=' -f2- || true)"
  echo "${val:-$default}"
}

set_env_var() {
  local key="$1" val="$2"
  if grep -qE "^${key}=" .env 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${val}|" .env
  else
    printf '%s=%s\n' "$key" "$val" >> .env
  fi
}

echo
echo "Checking for host port conflicts..."

# Ports already published by THIS project's own containers (if a previous
# run is still up) are not conflicts — docker compose reconciles those in
# place. Only a port held by something else is a real problem.
OWN_PORTS=""
for cid in $(docker compose ps -aq 2>/dev/null || true); do
  OWN_PORTS="${OWN_PORTS}
$(docker port "$cid" 2>/dev/null | grep -oE ':[0-9]+$' | tr -d ':' || true)"
done

port_is_own() {
  printf '%s\n' "$OWN_PORTS" | grep -qx "$1" || return 1
}

port_busy_on_host() {
  ss -H -ltn "sport = :$1" 2>/dev/null | grep -q . || return 1
}

port_claimed_this_run() {
  local p="$1" u
  for u in "${CLAIMED_PORTS[@]:-}"; do
    [ "$u" = "$p" ] && return 0
  done
  return 1
}

find_free_port() {
  local p="$1"
  while port_claimed_this_run "$p" || { ! port_is_own "$p" && port_busy_on_host "$p"; }; do
    p=$((p + 1))
  done
  echo "$p"
}

# var:default pairs for every host port docker-compose.yml publishes.
PORT_SPECS=(
  "HOST_HTTP_PORT:80"
  "HOST_HTTPS_PORT:443"
  "HOST_PROXY_PORT_4321:4321"
  "HOST_PROXY_PORT_3000:3000"
  "HOST_MAILHOG_PORT:8025"
  "HOST_DEBUG_PORT:9229"
  "HOST_POSTGRES_PORT:5432"
  "HOST_REDIS_PORT:6379"
  "HOST_MINIO_CONSOLE_PORT:9001"
  "HOST_WEBSITE_PORT:4322"
)

CLAIMED_PORTS=()
CONFLICTS_FOUND=0
for spec in "${PORT_SPECS[@]}"; do
  var="${spec%%:*}"
  default="${spec##*:}"
  current="$(get_env_var "$var" "$default")"
  if port_claimed_this_run "$current" || { ! port_is_own "$current" && port_busy_on_host "$current"; }; then
    new_port="$(find_free_port "$current")"
    echo "  Port ${current} (${var}) is already used by another process on this host — switching to ${new_port}."
    current="$new_port"
    CONFLICTS_FOUND=1
  fi
  # Always persist, even unchanged — backfills vars missing from an .env
  # written by an older version of this script (otherwise `set -u` below
  # trips on whichever var was never conflicted-and-written before).
  set_env_var "$var" "$current"
  CLAIMED_PORTS+=("$current")
done

if [ "$CONFLICTS_FOUND" -eq 0 ]; then
  echo "  No conflicts — all default ports are free (or already ours)."
fi

# ---------------------------------------------------------------------------
# Keep MINIO_PUBLIC_URL_BASE (the address the server stamps into every
# item_images.url it writes — server/src/config.ts) in sync with this host's
# actual LAN IP. A stale value here doesn't fail loudly like a stuck port —
# it silently bakes a dead address into every image URL the server writes
# from then on, which is exactly what happened before this check existed
# (see docs/steps-validation-migration-ts07.md's sibling investigation).
#
# Skipped once real Cloudflare R2 credentials are configured (R2_ENDPOINT/
# R2_ACCESS_KEY/R2_SECRET_KEY all set): at that point uploads go straight to
# R2, not local MinIO, so the LAN IP + /media (nginx -> local MinIO proxy)
# is the WRONG address — it would silently point every new upload's public
# URL at a backend that never received the object. Real bug hit
# 2026-08-17: images/invoice PDFs got "Access Denied"/unreachable because
# this override kept re-stamping the LAN IP over the correct R2 public
# domain. Once R2 is configured, set MINIO_PUBLIC_URL_BASE by hand (or via
# CDN - Images system_settings) to the real R2 public URL/custom domain.
# ---------------------------------------------------------------------------
R2_ENDPOINT_SET="$(get_env_var R2_ENDPOINT "")"
R2_ACCESS_KEY_SET="$(get_env_var R2_ACCESS_KEY "")"
R2_SECRET_KEY_SET="$(get_env_var R2_SECRET_KEY "")"
if [ -n "$R2_ENDPOINT_SET" ] && [ -n "$R2_ACCESS_KEY_SET" ] && [ -n "$R2_SECRET_KEY_SET" ]; then
  echo "  MINIO_PUBLIC_URL_BASE left untouched — real R2 credentials are configured (see this block's comment)."
else
  LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
  if [ -z "$LAN_IP" ]; then
    LAN_IP="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')"
  fi
  LAN_IP="${LAN_IP:-127.0.0.1}"

  HTTPS_PORT_FOR_MEDIA="$(get_env_var HOST_HTTPS_PORT 443)"
  if [ "$HTTPS_PORT_FOR_MEDIA" = "443" ]; then
    NEW_MEDIA_BASE="https://${LAN_IP}/media"
  else
    NEW_MEDIA_BASE="https://${LAN_IP}:${HTTPS_PORT_FOR_MEDIA}/media"
  fi
  CURRENT_MEDIA_BASE="$(get_env_var MINIO_PUBLIC_URL_BASE "")"
  if [ "$CURRENT_MEDIA_BASE" != "$NEW_MEDIA_BASE" ]; then
    echo "  MINIO_PUBLIC_URL_BASE ${CURRENT_MEDIA_BASE:-<unset>} -> ${NEW_MEDIA_BASE}"
    set_env_var "MINIO_PUBLIC_URL_BASE" "$NEW_MEDIA_BASE"
  fi
fi

# Reload .env now that any conflicting ports / MINIO_PUBLIC_URL_BASE were
# rewritten, so the summary below reflects reality.
set -a
# shellcheck disable=SC1091
source .env
set +a

# ---------------------------------------------------------------------------
# Bring the stack up.
# ---------------------------------------------------------------------------

echo
echo "Starting the development stack (docker compose up --build)..."
if [ "$DETACH" -eq 1 ]; then
  if ! docker compose up --build -d; then
    echo >&2
    echo "docker compose up failed even after the port preflight check." >&2
    echo "Cleaning up the partially-started stack..." >&2
    docker compose down >/dev/null 2>&1 || true
    exit 1
  fi
else
  echo "Running in foreground — Ctrl+C stops the stack."
fi

cat <<EOF

Stack is starting. Once containers report healthy, reach it from:
  This machine : https://localhost:${HOST_HTTPS_PORT}      (or http://localhost:${HOST_HTTP_PORT}, redirects to https)
  Any LAN device: https://${LAN_IP}:${HOST_HTTPS_PORT}     (or http://${LAN_IP}:${HOST_HTTP_PORT})

The TLS cert is self-signed for CN=webapp-node.io — browsers will warn on
first visit; that's expected, just accept/continue.

If a LAN device times out instead of getting a TLS warning, the host
firewall is blocking the ports. On this host that would be, e.g.:
  sudo ufw allow ${HOST_HTTP_PORT}/tcp ${HOST_HTTPS_PORT}/tcp ${HOST_PROXY_PORT_3000}/tcp ${HOST_PROXY_PORT_4321}/tcp

Useful follow-ups:
  docker compose ps           # container status
  docker compose logs -f      # tail all logs
  docker compose down         # stop everything
EOF

if [ "$DETACH" -eq 0 ]; then
  exec docker compose up --build
fi
